---

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md
- name: Install cfssl
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.6.1/cfssl_1.6.1_linux_amd64
    dest: /usr/local/bin/cfssl
    mode: '0550'

- name: Install cfssljson
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.6.1/cfssljson_1.6.1_linux_amd64
    dest: /usr/local/bin/cfssljson
    mode: '0550'

- name: Create certs dir
  ansible.builtin.file:
    path: "{{ certs_dir }}"
    state: directory

- name: Copy cfssl template files
  ansible.builtin.template:
    src: "templates/{{ item }}"
    dest: "{{ certs_dir }}"
  loop:
    - ca-config.json
    - ca-csr.json
    - admin-csr.json
    - kube-controller-manager-csr.json
    - kube-scheduler-csr.json
    - kube-proxy-csr.json
    - kubernetes-csr.json
    - service-account-csr.json

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#certificate-authority
- name: Generate the CA configuration file, certificate, and private key
  ansible.builtin.shell:
    cmd: /usr/local/bin/cfssl gencert -initca ca-csr.json | cfssljson -bare ca
    chdir: "{{ certs_dir }}"

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-admin-client-certificate
- name: Generate the admin client certificate and private key
  ansible.builtin.shell:
    cmd: /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes admin-csr.json | cfssljson -bare admin
    chdir: "{{ certs_dir }}"

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-controller-manager-client-certificate
- name: Generate the kube-controller-manager client certificate and private key
  ansible.builtin.shell:
    cmd: /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
    chdir: "{{ certs_dir }}"

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-kube-proxy-client-certificate
- name: Generate the kube-proxy client certificate and private key
  ansible.builtin.shell:
    cmd: /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy
    chdir: "{{ certs_dir }}"

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-scheduler-client-certificate
- name: Generate the kube-scheduler client certificate and private key
  ansible.builtin.shell:
    cmd: /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-scheduler-csr.json | cfssljson -bare kube-scheduler
    chdir: "{{ certs_dir }}"

- name:
  set_fact:
    k8s_controller_ips: "{{ hostvars['controller-0']['ipv4'] }},{{ hostvars['controller-1']['ipv4'] }},{{ hostvars['controller-2']['ipv4'] }}"

- name:
  set_fact:
    k8s_public_addr: "{{ hostvars['controller-0']['ipv4'] }}"
    k8s_hostnames: "{{k8s_controller_ips}},127.0.0.1,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-kubernetes-api-server-certificate
- name: Generate the Kubernetes API Server certificate and private key
  ansible.builtin.shell:
    cmd: "/usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -hostname=10.32.0.1,10.240.0.10,10.240.0.11,10.240.0.12,{{ k8s_public_addr }},{{ k8s_hostnames }} -profile=kubernetes kubernetes-csr.json | cfssljson -bare kubernetes"
    chdir: "{{ certs_dir }}"

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-service-account-key-pair
- name: Generate the service-account certificate and private key
  ansible.builtin.shell:
    cmd: /usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes service-account-csr.json | cfssljson -bare service-account
    chdir: "{{ certs_dir }}"

# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-kubelet-client-certificates
- name: Copy cfssl worker files
  ansible.builtin.template:
    src: "templates/worker-csr.json"
    dest: "{{ certs_dir }}/{{ item }}-csr.json"
  loop:
    - worker-0
    - worker-1
    - worker-2
- name: Generate a certificate and private key for each Kubernetes worker node
  ansible.builtin.shell:
    cmd: "/usr/local/bin/cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -hostname={{ item }},{{ hostvars[item]['ipv4'] }} -profile=kubernetes {{ item }}-csr.json | cfssljson -bare {{ item }}"
    chdir: "{{ certs_dir }}"
  loop:
    - worker-0
    - worker-1
    - worker-2
