---
- name: Provision k8s cluster
  hosts: controller-0
  remote_user: root
  vars_files:
    - vars.yml

  roles:
    - role: certs
      tags: [ certs ]
    - role: kubeconfig
      tags: [ kubeconfig ]